services:
  - type: web
    name: optify-backend
    env: node
    buildCommand: cd backend && npm install && npm rebuild bcrypt --build-from-source
    startCommand: cd backend && node app.js
    envVars:
      - key: NODE_VERSION
        value: 16.x
      - key: DB_HOST
        value: interchange.proxy.rlwy.net
      - key: DB_USER
        value: root
      - key: DB_PASS
        value: tcAjUKLaLDSDhJaShJTtxXgzNmFmERjG
      - key: DB_NAME
        value: railway
      - key: DB_PORT
        value: 26399